#!/sbin/openrc-run

depend() {
	use clock logger
	need localmount
	provide cron
}

start_pre() {
	# Make sure the cron dir exists
	set -- ${COMMAND_ARGS}
	while [ $# -ne 0 ]; do
		case ${1} in
			-c)
				shift
				mkdir -p ${1}
				break
				;;
			-c*)
				mkdir -p ${1#-c}
				break
				;;
		esac
		shift
	done
}

command_args="-f ${COMMAND_ARGS}"
command_background="true"
pidfile="/var/run/busybox-cron.pid"
command="/usr/sbin/crond"

# vim: noet ft=gentoo-init-d
